### ISSUE TITLE
git clone require username and password ?

### ISSUE THREAD

**Issue by csinsight** [cudeso/misp-scraper#11]
Why suddenly i need to enter username and password when try to git clone the repo ?

<img width="202" alt="misp-scraper credential" src="https://user-images.githubusercontent.com/117985321/201499580-87a39ba6-ceb3-4a50-b917-d12faf4e65a6.PNG">

**Comment by cudeso** [comment]
There has **not** been any change. `git clone https://github.com/cudeso/misp-scraper.git` without password should still work.

**Comment by cudeso** [comment]
No further follow-up, closing.
